E-Dernek/E-Dernek/Controllers/AboutController.cs
using E_Dernek.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Media;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace E_Dernek.Controllers
{
    public class AboutController : Controller
    {
        DataBaseContext db = new DataBaseContext();
        SoundPlayer uspjeh, neuspjeh;
        // GET: About
        public ActionResult InfoDernek(int id)
        {
            Dernek model = db.Dernek.Find(id);
            return View(model);
        }
        public string rezervacija1(int id)
        {
            if (Dernek.SpremiRezervaciju(id))
            {
                //if (uspjeh == null)
                //    uspjeh = new SoundPlayer(Url.Content(@"./Potvrda.wav"));
                //uspjeh.Play();    
                return "Uspjesno izvrsena rezervacija!";
                //return //("Potvrda.wav");
            }
            return "Nije uspjelo";
        }
    }
}

E-Dernek/E-Dernek/Controllers/DernekController.cs
using E_Dernek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Dernek.Controllers
{
    public class DernekController : Controller
    {
        DataBaseContext db = new DataBaseContext();

        // GET: Ponude
        public ActionResult Index()
        {
            return View(db.Dernek.ToList());
        }
        public string vratiIme(string id)
        {
            string ime = string.Empty;
            int x;
            Int32.TryParse(id, out x);
            Dernek dernek = db.Dernek.Find(x);
            if (dernek != null)
            {
                ime = dernek.Naziv;
            }
            return ime;
        }

        public string vratiSliku(string id)
        {
            string slika = string.Empty;
            int x;
            Int32.TryParse(id, out x);
            Dernek dernek = db.Dernek.Find(x);
            if (dernek != null)
            {
                slika = dernek.Slika;
            }
            return slika;
        }
    }
}

E-Dernek/E-Dernek/Controllers/HomeController.cs
using E_Dernek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Dernek.Controllers
{
    public class HomeController : Controller
    {
        DataBaseContext db = new DataBaseContext();
        public ActionResult Index()
        {
            /*
            var ID1 = db.Lokal.ToList();
            int id1 = ID1.Count();
            Lokal lok = new Lokal();
            lok.IDLokala = id1;
            lok.Naziv = "My Face";
            lok.Adresa = "Vilsonovo";
            lok.Broj = "033 299 299";
            db.Lokal.Add(lok);
            
            var samoZaID = db.Dernek.ToList();
            int id = samoZaID.Count();
            Dernek p = new Dernek();
            p.IDDerneka = id;
            p.Naziv = "Aca Lukas - My Face";
            p.IDLokala = id1;
            p.Kapacitet = 100;
            p.Slika = "https://expresstabloid.ba/wp-content/uploads/2018/03/DSC_0042-1.jpg";
            db.Dernek.Add(p);

            var ID2 = db.Lokal.ToList();
            int id2 = ID2.Count();
            Lokal lok1 = new Lokal();
            lok1.IDLokala = id2;
            lok1.Naziv = "Cinemas Club SLOGA";
            lok1.Adresa = "Centar";
            lok1.Broj = "033 400 299";
            db.Lokal.Add(lok1);

            var samoZaID1 = db.Dernek.ToList();
            int id3 = samoZaID1.Count();
            Dernek p1 = new Dernek();
            p1.IDDerneka = id3;
            p1.Naziv = "Severina - Cinemas Club SLOGA";
            p1.IDLokala = id2;
            p1.Kapacitet = 70;
            p.Slika = "https://www.zadar.travel/images/original/Severina_1311711241.jpg";
            db.Dernek.Add(p1);
            db.SaveChanges();*/
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View(db.Dernek.ToList());
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

E-Dernek/E-Dernek/Views/Home/About.cshtml
@model IEnumerable<E_Dernek.Models.Dernek>
@using Microsoft.AspNet.Identity
@{
                /**/

                /**/

                ViewBag.Title = "Derneci";
}
<html>
<head>
    <style>
        #container {
            background-color: green;
            width: 100%;
            height: 100px;
        }

        .ponuda {
            background-color: red;
            width: 33%;
            height: 60px;
            border: 1px solid #000;
            float: left;
        }
    </style>
</head>
<body>
    <div class="main">
        <div class="jumbotron" resource="">
            <h1>Odaberite trazeni dernek!</h1>
        </div>
        <p>@Html.ValidationMessage("pokazi", new { @style = "color:red" })</p>
        @foreach (var item in Model)
        {
        <div class="col-md-4">
            <img src="@Html.Action("vratiSliku", "Dernek", new { id = item.IDDerneka })" width="272" height="180" alt="Moskva" onclick="location.href='@Url.Action("InfoDernek","About", new { id = item.IDDerneka })'" class="responsive">
            <h3>@Html.Action("vratiIme", "Dernek", new { id = item.IDDerneka })</h3>

            <p>
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                    <style>
                        .block {
                            display: block
                            border: none;
                            background-color: #4CAF50;;
                            width: 100%;
                            color: white;
                            padding: 14px 28px;
                            font-size: 16px;
                            cursor: pointer;
                            text-align: center;
                        }

                            .block:hover {
                                background-color: #ddd;
                                color: black;
                            }
                    </style>
                </head>
                <body>
                    @using Microsoft.AspNet.Identity
                    @if (Request.IsAuthenticated)
                    {
                        <button class="block" onclick="location.href='@Url.Action("InfoDernek", "About")'">Rezerviši</button>
                    }

                </body>
            </p>
            <br> <br />
        </div>
    }
        </div>
</body>

</html>

E-Dernek/E-Dernek/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Najtrazeniji lokali";
}
<body align ="center">
<h1 align ="center">@ViewBag.Title</h1>
<h2 align ="center">JUNI 2018</h2>
<div align ="center">
    <h3 align ="center"> WALTER </h3>
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11507.676306523643!2d18.399198098383568!3d43.85750593167079!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4758c8d95922ba2d%3A0x5a29d7668ba4c946!2sDas+ist+Walter+Club!5e0!3m2!1sen!2sba!4v1528681083872" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<div align ="center">
    <h3 align ="center"> MY FACE </h3>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2877.1004923025716!2d18.39501511493663!3d43.85374574745836!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4758c921fa754427%3A0xfcfff9278eef6a83!2sMy+Face!5e0!3m2!1sen!2sba!4v1528681143448" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<div align ="center">
    <h3 align ="center"> CINEMAS CLUB SLOGA </h3>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2876.811866373433!2d18.41659501493682!3d43.85972794707011!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4758c8d06d1d292f%3A0xaeccf1639e3ce15a!2sCinemas+Sloga!5e0!3m2!1sen!2sba!4v1528681188717" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
</body>

E-Dernek/E-Dernek/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <H1 align="Center"> E - DERNEK</H1>
    <h2 align="center">Sviđa vam se šta vidite na slikama ispod? Saznajte kako im se možete pridružiti, u samo par klikova, sa Vašeg kauča!</h2>
    <!--<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>-->
</div>
<div id="slike" class="carousel slide" data-ride="carousel" style="margin-top:-5px">
    <ol class="carousel-indicators">
        <li data-target="#slike" data.slide-to="0" class="active"></li>
        <li data-target="#slike" data.slide-to="1"></li>
        <li data-target="#slike" data.slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/Content/Images/party1.jpg" />
            <div class="carousel-caption">
                <p></p>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/Images/party2.jpg" />
            <div class="carousel-caption">
                <p></p>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/Images/party3.jpg" />
            <div class="carousel-caption">
                <p</p>
            </div>
        </div>
    </div>

    <a class="left carousel-control" herf="slike" role="button" data-slide="prev">
        <span class="icon-prev"></span>

    </a>

    <a class="right carousel-control" herf="slike" role="button" data-slide="next">
        <span class="icon-next"></span>
        <span class="sr-only">Next</span>
    </a>
    <script>
        $("#carousel").carousel(
            {
                interval: 2000

            });
    </script>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>KALENDAR BUDUĆIH DOGAĐAJA</h2>
        <p>
            <iframe src="https://calendar.google.com/calendar/b/1/embed?showTitle=0&amp;showNav=0&amp;showPrint=0&amp;showTz=0&amp;height=300&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=l7oca420jshmdjjm3hek34ot6k%40group.calendar.google.com&amp;color=%23B1440E&amp;ctz=America%2FLos_Angeles" style="border-width:0" width="350" height="300" frameborder="0" scrolling="no"></iframe>
        </p>
    </div>
    <div class="col-md-6">
        <h2>e - Dernek Tim</h2>
        <p>
            Mi smo samo dva momka koja jednu noc nisu mogli da rezervišu stol, u MY FACE-u, za Seku Aleksić, zbog gužve na telefonima. 
            Sve ostalo je plod naseg truda i rada :). Nadam se ćete uživati i javiti nam se sa sugestijama.
        </p>
    </div>
    <!--<div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>-->
</div>
<div class="row">
    <h3 align="Center"> Ideja je da olakšamo mladima, a i lokalima, proces rezervacije stolova, te automatizujemo cijeli proces.</h3>
    <h4 align="Center"> Izgled registracije lokala</h4>
    <div class="item">
        <img src="~/Content/Images/uwpizgled.jpg" />
        <div class="carousel-caption">
            <p></p>
        </div>
    </div>
</div>